### ISSUE TITLE
Provide a working example

### ISSUE THREAD

**Issue by janodev** [promet/PRAugmentedReality#19]
The PRAR-Example project is trying to fetch data from the hardcoded URL http://192.168.1.51/prometar/prar/ar_object/0 It would be nice to read a local file for example purposes, or provide some pointers on how to setup that information.

**Comment by glesage** [comment]
Indeed, this was intended to work with a Drupal Module that is currently still under review... The module will also be turned into a distribution and possible a standalone test site soon.

https://drupal.org/node/1994136

The difficulty with providing an example is that you wouldn't be able to know where the test is being done from. So you still have to either hard code a test current location or add a test GPX file to simulate that...

**Comment by glesage** [comment]
This is in the works, I am spining up a publicly accessible site as well as a GPX to simulate the testing location.

**Comment by janodev** [comment]
Great news! thank you.

**Comment by glesage** [comment]
The site is up at http://prar.prometsource.com/ but I'm just waiting on a coworker to fix a dependency on the server. Some XML chef package is missing and breaking a few things, including the communication services... /:

**Comment by ezhes** [comment]
Still having problems. Can you explain how to use the TestLoc.gpx thats in the example? Or even how to do it in a fresh pod project?

**Comment by glesage** [comment]
Hey shusain93,

**Testing with the example**
Well it'l be super easy once I get that site up and running for testing. Everything is ready app-wise but the only thing missing is this site (as explained above).

Once it's working, all you have to do open the app, let it download any new data from this site, and then simulate this "test location" before turing the switch on (the only 1 switch on the main view)... This will simulate your location to be where I am, in the middle of all the test places, thus allowing you to see them as if they were around you.
I will update the wiki/getting started guide with directions once its ready... it should be in the next few days (:

**How to do it in a fresh project**
Refer to the [Getting started guide](https://github.com/promet/PRAugmentedReality/wiki/Getting-started-Guide#grabem-all-and-startem) for directions on using it in your own guide... add any issues if you think there is something which I should elaborate on...

Thanks!

**Comment by ezhes** [comment]
As stated in the Getting Started Guide, you say to set data as:

```
[arController startARWithData:arData];
```

What's the format for the NSData? How would I load in a GPX file?

**Comment by glesage** [comment]
Hey shusain93,

**Data stuff:**
You're right, I should've been a little more descriptive of the data required for AR. I just updated the [wiki guide](https://github.com/promet/PRAugmentedReality/wiki/Getting-started-Guide#what-do-i-feed-it) to include all the directions you need (:

Basically:  
The arData argument is an NSArray of NSDictionaries, where each dictionary contains the data for one AR Object. It'll be passed on to create objects of type [ARObject](https://github.com/promet/PRAugmentedReality/blob/master/Classes/AR/ARObject.h).  
The data you need to set in each dictionary is:

```
id      - key: "nid"
title   - key: "title"
lat     - key: "lat"
lon     - key: "lon"
```

Don't hesitate to ask anything else if things are unclear (:

**GPX file:**  
The test GPX file should already be part of the example app, if thats where you're using it in. You don't actually need to "load" anything, when you run the app on your device using xcode, you can "simulate location" from the bar at the bottom of your screen, between the code and debug area: ![https://dl.dropboxusercontent.com/u/30415492/GPX-thumb.png](https://dl.dropboxusercontent.com/u/30415492/GPX.png)

**Comment by glesage** [comment]
The site is finally up and running! @j4n0 
I will upload a new version to Cocoapods just for this (:
