### ISSUE TITLE
Out of Bounds Exception

### ISSUE THREAD

**Issue by ezhes** [promet/PRAugmentedReality#21]
Hello! I seem to be stuck. I'm trying to manually load code into the AR view, but with this code I crash with 
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
***`
I have my .m file over here: http://pastebin.com/58GjwaJU  . If you see anything that I'm doing wrong, please do tell.

**Comment by glesage** [comment]
You just need to `alloc & init` your objectOne because it gets autoreleased to early (ts only passed by reference and the reference is lost count is lost somehow unless you alloc/init.  

`NSMutableDictionary *objectOne = [[NSMutableDictionary alloc] init];`  

(:

**Comment by ezhes** [comment]
@glesage So the camera opens up now, except even the the lat / long cooridinates are within view, they aren't on the view. Am I doing something wrong with the data setup?

**Comment by glesage** [comment]
Uhm they should be on the view, I'm seeing it here when I use your data... make sure you turn all around to see where it is...

**Comment by ezhes** [comment]
So sorry. I had my location set as London. No wonder it was out of range.

**Comment by glesage** [comment]
yea np
