### ISSUE TITLE
Problem with example project, and simple code from wiki

### ISSUE THREAD

**Issue by sigmundfridge** [promet/PRAugmentedReality#41]
The example program has issues with a corrupted storyboard and xib file so I am unable to test it.

Using the code provided on the wiki also causes a crash, because you have named one of the delegate functions 

```
arControllerUpdateFrame: 
```

whereas the code is looking for 

```
prarUpdateFrame:
```

At least I think that's the issue.

It would be really useful to have a super simple example project (i.e. reading the current location, and then creating some random markers around that location). 
I say this because I've used your simple wiki code (after changing the method to prarUpdateFrame) to do just this but I have to angle my camera at 45° to the sky to see the markers so I guess I'm doing something wrong. However, trying to work out what is wrong when comparing it to your complex example project is difficult.

**Comment by glesage** [comment]
Hm, creating random spots around the user location might be a good idea, I'll investigate (:

But btw, you should only have to worry about a few lines in the ViewController & ARView for AR. The rest of the classes are just for the data which it fetches on my example site http://prar.prometsource.com/

**Comment by sigmundfridge** [comment]
I'm working on a simple project just for my own sanity so I'll send it over once it's finished. I was unable to fix the xib and storyboard issues with the example project, but it could be a font issue (if you were using a custom one in any of the labels).
