### ISSUE TITLE
Newbie not being able to setup ARData

### ISSUE THREAD

**Issue by joaopaulogalvao** [promet/PRAugmentedReality#42]
Hello guys,

I have been through all topics, but still having some difficulty in setting up the data.

It might be some relatively simple issue with arrays and dictionaries syntax I am having trouble with, as I am a newbie.

I tried to setup it under the ARObject.m class as follows:
- (NSDictionary*)getARObjectData
  {
  NSArray *keys = @[@"id",@"title", @"latitude", @"longitude"];
  
  NSArray *values = @[[NSNumber numberwithInt: 1],
                     [NSString stringWithString:@"Test Avenue"],
                     [NSNumber numberWithFloat:-23.598599],
                     [NSNumber numberWithFloat:-46.668892]];
  
  return [NSDictionary dictionaryWithObjects:values forKeys:keys];
  }

Should I setup it somewhere else? or, Is it here the place where the ARObject is created?

Could you guys help me in showing where the data should be feed in?

Regards and thanks for the great project.

**Comment by glesage** [comment]
Hey!

Sorry I've been a little out of it for a while...

It seems the problem is that you are giving it "latitude" & "longitude" keys instead of "lat" & "lon"

(:
